# Problem 1

In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a= np.random.randint(0,10,5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.size)
# 4 - matris'i yeniden boyutlandırın
print(a.reshape(5,1))
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[4 0 6 4 3]
5
[[4]
 [0]
 [6]
 [4]
 [3]]
(5,)


# Problem 2

In [3]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
yeni= np.arange(1,10,2)
print(yeni)
# 2 - Oluşturduğunuz matrisi parçalayın
parca= yeni.reshape(5,1)
print(parca)
# 3 - Parçalanmış matrisleri birleştirin
butun= np.concatenate(parca)
print(butun)

[1 3 5 7 9]
[[1]
 [3]
 [5]
 [7]
 [9]]
[1 3 5 7 9]


# Problem 3

In [10]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
ara= np.arange(5,100,2) ###########3 bunasıl ya :,D
mat= 
# 2 - matris'in özelliklerini inceleyin
print(
    mat.shape()
    mat.ndim()
    mat.size()
)

[87 13  9 83 43 21 91 77 73 15]
