# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([23,30,12,10,1])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
b=sorted(a)
print(b)

[1, 10, 12, 23, 30]


# Problem 2

In [1]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a= np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b= np.arange(5,16)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c= np.arange(5,101,5)
print(c)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d= np.zeros(10)
print(d)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e= np.ones(10)
print(e)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f= np.linspace(0,100,5)
print(f)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g= np.random.randint(10,30,5)
print(g)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h= np.linspace(-1,1,10)
print(h)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
j= np.random.randint(10,50,(5,3))
print(j)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
k= sum(
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.


# 14- Üretilen dizinin elemanlarını tersten yazdırın.


# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[24 23 19 12 23]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[[31 24 32]
 [10 20 47]
 [32 21 29]
 [30 40 41]
 [25 28 28]]
[128 133 177]
